name: Update Version

on:
  push:
    tags:
      - 'v*'

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install toml CLI
        run: python -m pip install --upgrade toml-cli

      - name: Update Cargo.toml version
        run: |
          VERSION=$(echo $GITHUB_REF | sed -e 's/refs\/tags\/v//')
          toml set Cargo.toml package.version "$VERSION"

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Cargo.toml
          git commit -m "Update Cargo.toml version to $VERSION" || true
          git push
